spring.datasource.url=jdbc:mysql://localhost:3306/insurancecompany?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
jwt.secret=6712aef04959eee2d764753f57469d4513fff3991183faecad66195a1125657ec412bdcfd49411b38b4a8f762cafb61452b1180a9bfc02c18cbbe60b9f899a041b8ebcc7a041a8fd342be68a9c697ac29c5067142f86e56b8a2c53e98b8aed44ec37728cc7af1d590ba4362ae4ce35d94ed8eeb334c03455ce873d1caeb1d6431078b563b6bdda6dd541176b90ff434345b674927fbc26ba7d41400bc207176730b08defd34b30ccb84a4ae8b9d5cdccbff41b695d02e7ffd315e9b4dbd1a98638810eea9bd54990d48bed66daf6a5af5f6eca028e9eb065ab0a71d807bc77eaaa95982a9623fb3e21c85946be717171f9d10a462b274ca1b6b1fdac43c93c66
jwt.access.expiration=86400000
jwt.refresh.expiration=604800000
stripe.publishable.key=pk_test_51RHkSdQ3uSpbFZc5RxWJMe9VVbe2nSqmrqLSEDv4PR4RCLOh62IwNCXUNsK6t2KFIeSArZiwCWuP1iwxdBhqP7Oh00pXofQ90u
stripe.api.key=sk_test_51RHkSdQ3uSpbFZc5mmctVJbqsnTg8CvG4c0NWndW666ejwFPoG8TTsNvkiXUILWFtzLPLHYkmuyahYAKxGOlwIvR00lZbXBtTr

spring.mail.host=smtp.gmail.com
spring.mail.port=587


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#server.port=8443
#server.ssl.key-store=classpath:keystore.p12.old
#server.ssl.key-store-password=natasa
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=mycert
#server.ssl.client-auth=NONE
#server.ssl.trust-store=classpath:truststore.p12
#server.ssl.trust-store-password=natasa
#server.ssl.trust-store-type=PKCS12


server.port=8443
server.ssl.enabled=true

server.ssl.key-store=classpath:spring-keystore.p12
server.ssl.key-store-password=natasa
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=spring-server

server.ssl.trust-store=classpath:truststore.p12
server.ssl.trust-store-password=natasa
server.ssl.trust-store-type=PKCS12

#mTLS
server.ssl.client-auth=want


